config/routes.rb
Rails.application.routes.draw do

 root 'recipyes#index'

 devise_for :users, :path => 'u' 

 get 'users/index/:id', to: "users#index", as:"user_recipes"
 get 'users/list', to: "users#list_users", as: "list_users"
 get 'users/list/banned', to: "users#list_banned_users", as: "list_banned_users"
 get 'users/list/recipes', to: "users#list_of_recipes", as: "list_of_recipes"
 get 'users/list/comments', to: "users#list_of_comments", as: "list_of_comments"

 resources :categories, except:[:new,:show]

 resources :users, only: [:show, :destroy] do 
 	member do
 	 patch 'banned'
 	end
 	end
 
 resources :recipyes do
 resources :comments, only: [:create, :destroy]
  
  collection do
   get "search" 
   get "about"
   get "contact"
  end

  member do
   put 'like', to: 'recipyes#upvote'
	end
 end

 get '*path' => redirect('/')
end

app/controllers/recipyes_controller.rb
class RecipyesController < ApplicationController

 before_action :recipe_find, only:[:show, :edit, :update, :destroy, :upvote]
 before_action :authenticate_user!, only:[:create, :edit, :update, :destroy, :upvote]
 before_action :correct_user, only: [:edit, :update, :destroy]
 before_action :categories, only: [:new, :create, :edit]
 
 def index
  if params[:category]
   @category = Category.find_by(name: params[:category])
   @recipies = Recipe.where('category_id = ?', @category).paginate(page: params[:page], per_page:6).order('created_at DESC')
  else
   @recipies = Recipe.all.paginate(page: params[:page], per_page:6).order('created_at DESC')
  end
 end

 def new
  @recipe = Recipe.new
 end

 def create
  @user = current_user
  @recipe = @user.recipes.build(recipe_params)
  if @recipe.save
    flash[:success] = "#{@recipe.title.capitalize} was created"
   	redirect_to recipye_path(@recipe)
  else
 	  render :new
  end
 rescue Faraday::ConnectionFailed
 redirect_to recipye_path(@recipe)
 end

 def show 
  @comment = @recipe.comments.build
 end

 def edit
 end

 def update
  if @recipe.update(recipe_params)
 	flash[:success] = "Updated!"
 	redirect_to recipye_path(@recipe)	
  else
 	render :edit
  end
 rescue Faraday::ConnectionFailed
  redirect_to recipye_path(@recipe)
 end

 def destroy
  @recipe.destroy
 rescue Faraday::ConnectionFailed
  flash[:success] = "Destroyed!"
  redirect_to :back	
 end

 def search
  if params[:search].present?
	@recipies = Recipe.search(params[:search]) 
  else
	flash[:alert] = "Typing your key words"
  redirect_to :back
  end
 rescue Faraday::ConnectionFailed
  render_500
 end

 # Static pages About, Contact.

 def about
 end

 def contact
 end

 #Voiting 
 
 def upvote 
  @recipe.upvote_by current_user
  redirect_to action: 'show'
 end

 private
 
 def correct_user
  @recipe_compare = current_user.recipes.find_by(id: params[:id])
  if @recipe_compare.nil? && current_user.admin == false
	flash[:error] = "Permission denied!"
	redirect_to recipye_path(@recipe) 
  end 
 end

 def recipe_params
  params.require(:recipe).permit(:title, :description, :image, :category_id, ingredients_attributes:[:id, :name, :_destroy], directions_attributes: [:id, :step, :_destroy])
 end

 def recipe_find
  @recipe = Recipe.find(params[:id])
 rescue ActiveRecord::RecordNotFound
  render_404
 end

 def categories
  @categories = Category.all
 end

end

app/helpers/recipyes_helper.rb
module RecipyesHelper
end

app/views/recipyes/_direction_fields.html.haml
.form-inline.clearfix
 .nested-fields
  = f.input :step, required:false, label:false, input_html:{class:'form-control form-input'}
  = link_to_remove_association 'Remove', f, class:'form-button btn btn-default'

app/views/recipyes/_footer.html.haml
%ul
 %li= link_to 'Contact', contact_recipyes_path
 %li= link_to 'About', about_recipyes_path 
    

app/views/recipyes/_form.html.haml
#some
 -if @recipe.errors.any?
  .alert-danger.errors
   %p
    =pluralize("#{@recipe.errors.count}","Error")
    prevented this recipy from saving:
   %ul
    -@recipe.errors.full_messages.each do |msg|
     %li= msg
 .panel-body
  =f.input :title, required:false, label:false, input_html:{class:"form-control", placeholder:"Title"}
  %br
  =f.input :image, required:false, label:false, input_html:{class:"form-control"}
  %br
  =f.input :description, required:false, label:false, input_html:{class:"form-control form-control2", placeholder:"Description"}
  %br 
  =f.collection_select :category_id, @categories, :id, :name, {prompt:"Chose a category"}, class:"form-control" 
  .row
   .col-md-6
    %h3 Ingredients
    #ingredients
     = f.simple_fields_for :ingredients do |ingredient|
      = render "ingredient_fields", f: ingredient
     .links 
      = link_to_add_association '+ Ingredient', f, :ingredients, class: 'form-button btn btn-default'
   .col-md-6
    %h3 Directions
    #directions
     = f.simple_fields_for :directions do |direction|
      = render "direction_fields", f: direction
     .links 
      = link_to_add_association 'Step', f, :directions, class: 'form-button btn btn-default'
 %br
 
 

app/views/recipyes/_index.html.haml
-@recipies.each_slice(3) do |recipe|
 .row
  -recipe.each do |recipe|
   .col-md-4 
    .recipe 
     .image_wrapper
      =link_to recipye_path(recipe) do
       =image_tag recipe.image.url(:medium) 
       
     %h2= link_to recipe.title.capitalize, recipye_path(recipe)
%p= will_paginate @recipies, inner_window:1, outer_window:0

app/views/recipyes/_ingredient_fields.html.haml
.form-inline.clearfix
 .nested-fields
  = f.input :name, required:false, label:false, input_html:{class:'form-control form-input'}
  = link_to_remove_association 'Remove', f, class:'form-button btn btn-default'

app/views/recipyes/about.html.haml
.about_contact
 %h3
  %br/
  %p The book of recipes, comfortable place for keeping your recipes,
  %p and sharing them with your friends and relatives. 
  %br/

app/views/recipyes/contact.html.haml
.about_contact
 %h3 
  %br/
  %p Your remarks, wishes about the site working or offers, you may send  
  %p on the email: alex.radzyuk@gmail.com 
  %br/
  

app/views/recipyes/edit.html.haml
.new_edit_titles
 %h2 Edit recipe
%hr
= simple_form_for @recipe, url:"/recipyes/#{@recipe.id}", html: {multipart: true} do |f|
 = render 'form', f:f
 = link_to 'Back', :back, class:'btn btn-default'
 = f.button :submit, value:"Update", class:'btn btn-default success'
 

app/views/recipyes/index.html.haml
=render 'index'

app/views/recipyes/new.html.haml
.new_edit_titles
 %h2 New Recipe
%hr

= simple_form_for @recipe, url:"/recipyes/#{@recipe.id}", html: {multipart: true} do |f|
 = render 'form', f:f
 = link_to 'Back', :back, class:'btn btn-default'
 = f.button :submit, value:"Create", class:'btn btn-default success'
 

app/views/recipyes/search.html.haml
#search_result
 %h2 Search result..
%hr
=render 'index'

app/views/recipyes/show.html.haml
.main_content
 
 .row
  .col-md-6
   #recipe_top
   = image_tag @recipe.image.url(:medium, class:"recipe_image")  
  
  .col-md-6
   #recipe_info
    %h3= @recipe.title.capitalize
    %p= to_link(@recipe.description.capitalize)
 
 .row
  .col-md-6
   #ingredients
    %h2 Ingredients
    %ul
     - @recipe.ingredients.each do |ingredient|
      %li
       %input{ :type=>"checkbox" }
       =ingredient.name.capitalize

 
  .col-md-6
   #directions
    %h2 Directions
    %ul
     - @recipe.directions.each do |direction|
      %li
       %input{ :type=>"checkbox" }
       = direction.step.capitalize

%p
 = "Was created at #{@recipe.created_at.strftime("%d %B")} by" 
 = link_to "#{@recipe.user.email}", user_path("#{@recipe.user.id}")
%br/
%p
 =link_to 'Back', :back, class:'btn btn-default'
 =link_to like_recipye_path(@recipe), method: :put, class:"btn btn-default vote" do
  %span.glyphicon.glyphicon-heart
   = @recipe.votes_for.size
 - if user_signed_in?
  =link_to 'Edit', edit_recipye_path(@recipe),class:'btn btn-default'
  =link_to 'Delete', recipye_path(@recipe) , method: :delete, data:{:confirm=>"Are you sure?"},class:'btn btn-default danger'

%hr
%h2#user_detail
 Comments 
 %span{class:'badge'}= @recipe.comments.count 
%br
- @recipe.comments.each do |c| 
 - unless c.nil? || c.created_at.nil?
  %table{:border => "0",class:'table table-striped commenter'}
   %tr
    %th.user_avatar= link_to image_tag(c.user.avatar.url(:thumb), class:"avatar"), user_path(c.user_id)
    %th.text_comment= to_link(c.body)
   %tr
    %th.commenter= c.user.name 
    %th.comment_date= c.created_at.strftime("%d %B %Y")
    - if user_signed_in? 
     - if c.user_id == current_user.id || current_user.admin
      %th.comment-delete= link_to "Delete", recipye_comment_path(@recipe, c), method: :delete, class:'comment-delete', data:{confirm:'Really?'}
%hr
= render '/comments/form_for_comment'