config/routes.rb
Rails.application.routes.draw do

 root 'recipyes#index'

 devise_for :users, :path => 'u' 

 get 'users/index/:id', to: "users#index", as:"user_recipes"
 get 'users/list', to: "users#list_users", as: "list_users"
 get 'users/list/banned', to: "users#list_banned_users", as: "list_banned_users"
 get 'users/list/recipes', to: "users#list_of_recipes", as: "list_of_recipes"
 get 'users/list/comments', to: "users#list_of_comments", as: "list_of_comments"

 resources :categories, except:[:new,:show]

 resources :users, only: [:show, :destroy] do 
 	member do
 	 patch 'banned'
 	end
 	end
 
 resources :recipyes do
 resources :comments, only: [:create, :destroy]
  
  collection do
   get "search" 
   get "about"
   get "contact"
  end

  member do
   put 'like', to: 'recipyes#upvote'
	end
 end

 get '*path' => redirect('/')
end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :recipes, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_attached_file :avatar, styles: {medium: "200x200>", thumb: "70x70>" }, default_url: "missing_avatar.png", styles: {thumb: "70x70>" }
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  validates_with AttachmentSizeValidator, attributes: :avatar, less_than: 1.megabytes
 	
 	validates :email, uniqueness: true
 	validates :name, presence:true
 	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :user_find, only:[:index, :show, :banned, :destroy]
	before_action :user_params, only:[:banned]
  before_action :if_admin, except: [:index, :edit, :show]

 def index
	@recipies = @user.recipes.paginate(page: params[:page], per_page:6).order('created_at DESC')
 end

 def list_users
 	@users = User.where(admin:false).paginate(page: params[:page], per_page:10).order('created_at DESC')
 end
 
 def list_banned_users
 	@users = User.where(banned:true).paginate(page: params[:page], per_page:10).order('created_at DESC')
  render :list_users
 end
 
 def list_of_recipes
  @recipes = Recipe.all.paginate(page: params[:page], per_page:20).order('created_at DESC')
  render :list_users
 end
 
 def list_of_comments
  @comments = Comment.all.paginate(page: params[:page], per_page:10).order('created_at DESC')
  render :list_users
 end

 def banned
  @user.update_attributes(user_params) 
  flash[:success] = "User was unlocked!"  if ! @user.banned?
  flash[:error] = "User was locked!" if @user.banned?
  redirect_to :back
 end

 def destroy
 	@user.destroy 
 	flash[:error] = "#{@user.name.capitalize} was destroyed!"
 	redirect_to list_users_path
 end

 def edit
 end

 def show
  @users = User.where(admin:false)
  @banned_users_count = User.where(banned:true).count
  @categories = Category.all
  @recipes = Recipe.all
  @comments = Comment.all
 end

 private

 def user_find
  @user = User.find(params[:id]) 
 rescue ActiveRecord::RecordNotFound
  render_404
 end

 def user_params
 	params.require(:user).permit(:banned)
 end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.haml
#user_detail
 %h2= "#{@user.name.capitalize} recipes:"
%hr
= render partial:"recipyes/index"
%hr
 %p= link_to 'Back', user_path(@user), class:"btn btn-default"

app/views/users/list_users.html.haml
- if current_page?("/users/list/recipes")
 
 %h3#user_detail List of all recipes:
 %hr
 %table{:border => "1",class:'table table-striped'}
  %tr
   %th Title
   %th Created_by  
   %th Category
   %th Created_at
   %th{:colspan=>"2"} Action
  -@recipes.each do |recipe|
   %tr
    %td=link_to recipe.title.capitalize, recipye_path(recipe)
    %td=link_to recipe.user.name, user_path(recipe.user_id)
    %td
     = recipe.category.name if recipe.category
     = "Unknown" if ! recipe.category
    %td=recipe.created_at.strftime("%B %e, %Y %l:%M %p")
    %td=link_to 'Edit', edit_recipye_path(recipe)
    %td=link_to 'Del', recipye_path(recipe), method: :delete, data:{confirm:"Delete '#{recipe.title.capitalize}'?"}, class:'del'
 %hr/
 = will_paginate @recipes, inner_window:1, outer_window:0, renderer: BootstrapPagination::Rails

- elsif current_page?("/users/list/comments")
 
 %h3#user_detail List of all comments:
 %hr
 %table{:border => "1",class:'table table-striped comments'}
  %tr
   %th Comment
   %th Created_by  
   %th Created_at
   %th Action
  -@comments.each do |comment|
   %tr
    %td=link_to comment.body.capitalize, recipye_path(comment.recipe_id)
    %td=link_to comment.user.name, user_path(comment.user_id)
    %td=comment.created_at.strftime("%B %e, %Y %l:%M %p")
    %td=link_to 'Del', recipye_comment_path(comment.recipe_id, comment), method: :delete, data:{confirm:"Delete?"}, class:'del'
 %hr/
 = will_paginate @comments, inner_window:1, outer_window:0, renderer: BootstrapPagination::Rails

- elsif current_page?("/users/list") || current_page?("/users/list/banned")

 #user_detail
  %h3= "List of all users:" if current_page?("/users/list")
  %h3= "List of banned users:" if current_page?("/users/list/banned")
 %hr
 - @users.each do |u|
  - if ! u.admin
   %table{:border => "1",class:'table table-striped users'}
    %tr
     %td= link_to image_tag(u.avatar.url(:thumb), class:"avatar"), user_path(u)
     %td= u.name.capitalize
     %td= u.email
     %td
      = form_for u, url:"/users/#{u.id}/banned" do |f|
       - if ! u.banned?
        = f.label 'Lock user'
        = f.check_box :banned, {},true, checked:""
       - else
        = f.label 'Unlock user'
        = f.check_box :banned, {},false, checked:""
       %p= f.submit "Submit", class: "button small btn-default" 
     - if ! current_page?("/users/list/banned")
      %td= link_to 'Delete', user_path(u), method: :delete, class:'del', data:{confirm:"Destroy user?"} 
  %hr
  = will_paginate @users, inner_window:1, outer_window:0, renderer: BootstrapPagination::Rails

%hr
%p= link_to 'Back', user_path(current_user), class:"btn btn-default"


 
   

app/views/users/show.html.haml
- if user_signed_in?
 - if current_user.admin 
  %h2#user_detail Manage resource:
  %br
  %table{:border => "1",class:'table table-striped'}
   %tr
    %td= link_to "Users (#{@users.count})", list_users_path 
    %td= link_to "Banned users (#{@banned_users_count})", list_banned_users_path
    %td= link_to "Categories (#{@categories.count})", categories_path
    %td= link_to "Recipes (#{@recipes.count})", list_of_recipes_path
    %td= link_to "Comments (#{@comments.count})", list_of_comments_path
%hr/

#user_detail  
 %h2 User detail:
 %hr/
 %p
  %style="word-spacing:13px;"
  %b
  = @user.name.capitalize
  = image_tag @user.avatar.url(:thumb), class:"avatar"
  
 %p= @user.email
 %p= "Created: #{@user.created_at.to_s(:short)}"
  
 - if @user.recipes.count == 0
  = render text: "Has #{@user.recipes.count} recipes" 
 - elsif @user.recipes.count < 2
  = link_to "Has #{@user.recipes.count} recipe", user_recipes_path(@user)
 - else
  = link_to "Has #{@user.recipes.count} recipes", user_recipes_path
 %hr/
 - if user_signed_in?
  - if current_user.admin || current_user.id == @user.id
   
   = link_to "Edit profile", edit_user_registration_path, class:"btn btn-primary"

 %hr/
 = link_to "Back",:back, class:"btn btn-default" 