config/routes.rb
Rails.application.routes.draw do

 root 'recipyes#index'

 devise_for :users, :path => 'u' 

 get 'users/index/:id', to: "users#index", as:"user_recipes"
 get 'users/list', to: "users#list_users", as: "list_users"
 get 'users/list/banned', to: "users#list_banned_users", as: "list_banned_users"
 get 'users/list/recipes', to: "users#list_of_recipes", as: "list_of_recipes"
 get 'users/list/comments', to: "users#list_of_comments", as: "list_of_comments"

 resources :categories, except:[:new,:show]

 resources :users, only: [:show, :destroy] do 
 	member do
 	 patch 'banned'
 	end
 	end
 
 resources :recipyes do
 resources :comments, only: [:create, :destroy]
  
  collection do
   get "search" 
   get "about"
   get "contact"
  end

  member do
   put 'like', to: 'recipyes#upvote'
	end
 end

 get '*path' => redirect('/')
end

app/models/category.rb
class Category < ActiveRecord::Base

 has_many :recipes
 validates :name, presence:true, uniqueness: true, length:{maximum:50}

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

 before_action :if_admin
 before_action :find_category, except:[:index, :create]
 before_action :share_variables, except:[:destroy]

  def index
    @category = Category.new
  end

  def create
  @category = Category.new(params[:category].permit(:name))
   if @category.save
    flash[:success] = "Was added"
    redirect_to :back
   else
    render :index
  end
  end

  def edit
   render :index
  end

  def update
   if @category.update(params[:category].permit(:name))
    flash[:success] = "Updated"
    redirect_to categories_path
   else
    render :index
   end
  end

  def destroy
   @category.destroy
   flash[:success] = "'#{@category.name.capitalize}' was destroyed"
   redirect_to categories_path
  end

 private

  def share_variables
   @categories = Category.all.paginate(page: params[:page], per_page:10).order('created_at DESC')
  end

  def find_category
   @category = Category.find(params[:id])
  rescue ActiveRecord::RecordNotFound
   render_404
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form_for_category.html.haml
#some
 -if @category.errors.any?
  .alert-danger.categories_errors
   =pluralize("#{@category.errors.count}","Error")
   prevented this category from saving:
   %ul
    -@category.errors.full_messages.each do |msg|
     %li= msg
 =f.input :name, label:false, input_html:{class:"form-control", placeholder:"Name of the new category"}
 %br/
 .panel-body-category-form
 %p
  =link_to 'Cancel', categories_path, class: 'btn btn-default'
  =f.submit :Save, class:'btn btn-default'
 %br
  

app/views/categories/index.html.haml
#user_detail
 %h3 Ceategories list
%br
%table{:border => "1",class:'table table-striped'}
 %tr
  %th Name
  %th{:colspan=>"2"} Action  
 -@categories.each do |category|
  %tr
   %td=category.name.capitalize
   %td=link_to 'Edit', edit_category_path(category)
   %td=link_to 'Del', category_path(category), method: :delete, data:{confirm:"Delete #{category.name.capitalize}"}, class:'del'
%br/
%p= will_paginate @recipies, inner_window:1, outer_window:0, renderer: BootstrapPagination::Rails
%p
 = simple_form_for @category do |f|
  = render 'form_for_category', f:f
  %hr
 %p= link_to 'Back', user_path(current_user), class:"btn btn-default"


  