config/routes.rb
Rails.application.routes.draw do

 root 'recipyes#index'

 devise_for :users, :path => 'u' 

 get 'users/index/:id', to: "users#index", as:"user_recipes"
 get 'users/list', to: "users#list_users", as: "list_users"
 get 'users/list/banned', to: "users#list_banned_users", as: "list_banned_users"
 get 'users/list/recipes', to: "users#list_of_recipes", as: "list_of_recipes"
 get 'users/list/comments', to: "users#list_of_comments", as: "list_of_comments"

 resources :categories, except:[:new,:show]

 resources :users, only: [:show, :destroy] do 
 	member do
 	 patch 'banned'
 	end
 	end
 
 resources :recipyes do
 resources :comments, only: [:create, :destroy]
  
  collection do
   get "search" 
   get "about"
   get "contact"
  end

  member do
   put 'like', to: 'recipyes#upvote'
	end
 end

 get '*path' => redirect('/')
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
 %title Recipebox
 = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true 
 = javascript_include_tag 'application', 'data-turbolinks-eval' => false 
 = csrf_meta_tags 
%body
 %nav.navbar.navbar-default
  .container
   .navbar-brand= link_to "Recipe box", root_path

   #dropdown
    
    = button_tag "", class:"btn glyphicon glyphicon-chevron-down dropdown-toggle", type:"button", "data-toggle"=>"dropdown", id:"dropdownMenu1", "aria-haspopup"=>"true", "aria-expanded"=>"true"
    %ul.dropdown-menu{role:"menu", "aria-labelledby"=>"dropdownMenu1"}
     - for category in Category.all 
      %li= link_to category.name, recipyes_path(:category=>category.name)
      
   =form_tag search_recipyes_path, method: :get, role:"search" do
    =text_field_tag :search, params[:search], placeholder:'Search of a defined recipe...', class:'form-control'

   %ul.nav.navbar-nav.navbar-right
    %li= link_to "New recipe", new_recipye_path
    -if user_signed_in?
     %li= link_to "Admin accaunt", user_path(current_user) if current_user.admin?
     %li= link_to "Accaunt", user_path(current_user) if ! current_user.admin?
     %li= link_to "Sign out", destroy_user_session_path, method: :delete
    -else
     %li= link_to "Sign in", user_session_path
 #container_body 
  .container
   - flash.each do |type, msg|  
    - if type.include? 'error'
     = content_tag :div, msg, class:"alert alert-danger" 
    - elsif type.include? 'notice' 
     = content_tag :div, msg, class:"alert alert-info" 
    - elsif type.include? 'alert' 
     = content_tag :div, msg, class:"alert alert-info"
    - elsif type.include? 'notice' and current_page?(:controller => 'devise/sessions', :action => 'new')
     = content_tag :div, msg, class:"flash_align alert alert-info" 
    - elsif type.include? 'alert' and current_page?(:controller => 'devise/sessions', :action => 'new')
     = content_tag :div, msg, class:"flash_align alert alert-info" 
    - else 
     = content_tag :div, msg, class:"alert alert-#{type}"

   = yield
%br/
%footer{class:'footer'}
 .box
  =render 'recipyes/footer'
=# debug(params) if Rails.env.development?